name: Build and deploy Car Rent employee application

on:
  push:
    branches:
      - development
      - main
    paths:
      - 'car-rental/frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Create .env file for the Car Rent Frontend
        working-directory: car-rental/frontend/car-rental
        run: |
          echo "VITE_SERVER_URL=${{ secrets.RENTALFRONT_VITE_SERVER_URL }}" > .env

      - name: npm install, build, and test
        working-directory: car-rental/frontend/car-rental
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Ensure web.config is in dist folder
        working-directory: car-search/frontend/car-search
        run: |
          cp web.config dist/

      - name: Create a zip file of the dist directory
        working-directory: car-rental/frontend/car-rental
        run: |
          echo "Creating a zip file of the dist directory..."
          powershell -Command "Compress-Archive -Path dist/* -DestinationPath dist.zip"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: car-rental/frontend/car-rental/dist.zip

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'CarRentalFront'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_295963F9B03A4B73910E80645AAECB9D }}
          package: dist.zip # Point to the zipped package