name: Test build of Car Rent employee application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Create .env file for the Car Rent Frontend
        working-directory: car-search/frontend/car-search
        run: |
          echo "VITE_SERVER_URL=${{ secrets.RENTALFRONT_VITE_SERVER_URL }}" > .env

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Create a zip file of the dist directory
        working-directory: car-rental/frontend/car-rental
        run: |
          echo "Creating a zip file of the dist directory..."
          powershell -Command "Compress-Archive -Path dist/* -DestinationPath dist.zip"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: car-rental/frontend/car-rental/dist.zip