name: Test build of Car Rent API

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Create the .env file for Car Rental API
        working-directory: car-rental/backend/CarRentalAPI/CarRentalAPI
        run: |
          echo "ALLOWED_ORIGINS=${{ secrets.RENTALAPI_ALLOWED_ORIGINS }}" > .env
          echo "DATABASE_CONNECTION_STRING=${{ secrets.RENTALAPI_DATABASE_CONNECTION_STRING }}" >> .env
          echo "CAR_RENTAL_SECRET_KEY=${{ secrets.RENTALAPI_CAR_RENTAL_SECRET_KEY }}" >> .env

      - name: Update database
        run: |
          dotnet tool install --global dotnet-ef --version 8.*
          dotnet tool restore
          dotnet ef --project car-rental/backend/CarRentalAPI/CarRentalAPI/CarRentalAPI.csproj database update
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.SEARCHAPI_DATABASE_CONNECTION_STRING }}

      - name: Build with dotnet
        run: dotnet build car-rental/backend/CarRentalAPI --configuration Release

      - name: dotnet publish
        run: dotnet publish car-rental/backend/CarRentalAPI -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: "${{env.DOTNET_ROOT}}/myapp"