deploy:
  runs-on: ubuntu-latest
  needs: build
  if: github.ref == 'refs/heads/main'  # Only deploy if push is on main
  environment:
    name: 'Production'
    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  permissions:
    id-token: write  # Required for requesting the JWT

  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: List directory contents
      run: ls -la

    - name: Check if release.zip exists
      run: |
        if [ -f release.zip ]; then
          echo "release.zip exists"
        else
          echo "release.zip does not exist" && exit 1
        fi

    - name: Unzip artifact for deployment
      run: unzip release.zip -d .

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3F1DC0EA77B24A648E30D375E2519986 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_782341C661DD4E5C87561CB92B1185CF }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_20940CDCA0AD4150A991855A9DE84CFC }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'carsearch'
        slot-name: 'Production'
        package: .
