name: Build and deploy ASP.Net Core app to Azure Web App - carsearchapi

on:
  push:
    branches:
      - development  # Trigger build on development for testing changes
      - main         # Trigger build and deploy on main for production
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build car-search/backend/CarSearchAPI --configuration Release

      - name: dotnet publish
        run: dotnet publish car-search/backend/CarSearchAPI -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: "${{env.DOTNET_ROOT}}/myapp"

  deploy:
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Only run deployment if push is on main
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5DA27A1EC070421EAC9CFE9A5DD9B63D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_391FFE1FFACC4024ACBD0D511E01A2B4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_20574EF43DE540898AD4C2F77D7812D8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'carsearchapi'
          slot-name: 'Production'
          package: .
