# YAML for deploying Node.js app to Azure Web App - carsearch

name: Build and deploy Node.js app to Azure Web App - carsearch

on:
  push:
    branches:
      - development  # Trigger build on development for testing
      - main         # Trigger build and deploy on main for production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        working-directory: car-search/frontend/car-search
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # Ensure static assets are in the build directory
      - name: Move static assets to build folder
        run: |
          mkdir -p car-search/frontend/car-search/build/public
          cp -r car-search/frontend/car-search/public/* car-search/frontend/car-search/build/public

      - name: Zip artifact for deployment
        working-directory: car-search/frontend/car-search/build
        run: zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: car-search/frontend/car-search/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Only deploy if push is on main
    environment:
      name: 'Production'
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: List directory contents after download
        run: ls -la

      - name: Check if release.zip exists
        run: |
          if [ -f release.zip ]; then
            echo "release.zip exists"
          else
            echo "release.zip does not exist" && exit 1
          fi

      - name: Inspect release.zip contents
        run: unzip -l release.zip

      - name: Unzip artifact for deployment
        run: unzip release.zip -d temp-deployment-dir/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3F1DC0EA77B24A648E30D375E2519986 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_782341C661DD4E5C87561CB92B1185CF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_20940CDCA0AD4150A991855A9DE84CFC }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'carsearch'
          slot-name: 'Production'
          package: temp-deployment-dir/release.zip  # Ensure correct package path
